const CHUNK_HASH_SIZE = 5242880;
const FILE_ACCESS_PUBLIC = 'public';
const FILE_ACCESS_PRIVATE = 'private';
const FILE_ACCESS_PREMIUM = 'premium';

const ACCESS_TYPE_PUBLIC = 'public';

const DEFAULT_REQUEST_PER_SECOND = 5;

const CLI_CREATE_METHOD_FOR_PHP_API = 11;

export {
	CHUNK_HASH_SIZE,
	FILE_ACCESS_PUBLIC,
	FILE_ACCESS_PRIVATE,
	FILE_ACCESS_PREMIUM,
	ACCESS_TYPE_PUBLIC,
	DEFAULT_REQUEST_PER_SECOND,
	CLI_CREATE_METHOD_FOR_PHP_API,
};
